# fly.toml app configuration file generated for collection-ma on 2026-08-07T22:26:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'collection-ma'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'php artisan migrate --force'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_FALLBACK_LOCALE = 'fr'
  APP_LOCALE = 'fr'
  APP_URL = 'https://collection-ma.fly.dev'
  BROADCAST_CONNECTION = 'log'
  CACHE_STORE = 'database'
  DB_CONNECTION = 'pgsql'
  FILESYSTEM_DISK = 'local'
  PLATFORM_ADMIN_USER_ID = '1'
  QUEUE_CONNECTION = 'database'
  SESSION_DRIVER = 'database'

[[mounts]]
  source = 'collection_ma_storage'
  destination = '/var/www/storage'
  initial_size = '2gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  size = 'shared-cpu-2x'
